# Generated by Django 3.2.5 on 2021-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210718_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='negative_marks',
            field=models.FloatField(null=True),
        ),
    ]
