# Generated by Django 3.2.5 on 2021-07-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_negative_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='negative_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
