# Generated by Django 3.2.5 on 2021-07-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210719_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
