# Generated by Django 3.2.5 on 2021-07-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_test_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
