# Generated by Django 3.2.5 on 2021-07-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_test_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='topics',
            field=models.TextField(blank=True),
        ),
    ]
