# Generated by Django 3.2.5 on 2021-07-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_question_test'),
        ('tests', '0007_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
