# Generated by Django 3.2.5 on 2021-07-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_test_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
